# Generated by Django 3.1.1 on 2020-12-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201217_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commented_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
