# Generated by Django 3.1.1 on 2020-12-25 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='blog.post'),
        ),
    ]
