# Generated by Django 3.1.1 on 2021-01-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_activity_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categoryimage',
            field=models.ImageField(null=True, upload_to='assets/'),
        ),
    ]
