# Generated by Django 3.1.1 on 2021-04-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210411_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(null=True, related_name='categories', to='blog.Category'),
        ),
    ]
