# Generated by Django 3.1.1 on 2021-04-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210417_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='coverimage',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
