# Generated by Django 3.1.1 on 2021-04-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210417_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='blog.Category'),
        ),
    ]
